# Dubbo配置
dubbo:
  registry:
    address: zookeeper://localhost:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shop-pss?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
# 端口配置
server:
  port: 9000