dubbo:
  registry:
    address: zookeeper://localhost:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shop-pss?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.vin.pss.provider.dao: debug